[package]
name = "rpc-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.0"
lazy_static = "1.5.0"
serde = { version = "1.0.209", features = ["derive"] }
thiserror = "1.0.63"
url = "2.5.2"
zeroize = "1.8.1"
