[package]
name = "loadtest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
goose = "0.18.0"
tokio.workspace = true
simd-json.workspace = true
rand.workspace = true

[lints]
workspace = true
