[package]
name = "rpc-gateway-core"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.4"
alloy-chains.workspace = true
alloy-dyn-abi.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
anvil-rpc = { git = "https://github.com/whats-good/foundry", package = "anvil-rpc", rev = "b2bdf5ee58387021fe2048d47ea696bffaf44ffd" }
arc-swap.workspace = true
clap.workspace = true
dashmap = "6.1.0"
duration-str.workspace = true
futures.workspace = true
metrics.workspace = true
metrics-exporter-prometheus = "0.17.0"
nonempty.workspace = true
# quanta = "0.12.5" TODO: add this back
rand.workspace = true
reqwest.workspace = true
rpc-gateway-config.workspace = true
rpc-gateway-cache.workspace = true
rpc-gateway-eth.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true


[[bin]]
name = "rpc-gateway"
path = "src/bin/main.rs"

[lib]
path = "src/lib.rs"
